name: Build & Deploy TorizonCore
on:
  - push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy TorizonCore
    container:
      image: torizonextras/torizon-dev:dev
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          path: storage/
          key: tcb

      - name: Get Host Absolute Workspace Path
        run: |
          echo "${{ github.workspace }}" >> abs-path
          cat abs-path

      - name: Decode Credentials
        env:
          PLATFORM_CREDENTIALS: ${{ secrets.PLATFORM_CREDENTIALS }}
        run: |
          echo $PLATFORM_CREDENTIALS | base64 -d > credentials.zip

      - name: Build TorizonCore Image
        shell: xonsh {0}
        run: |
          xonsh ./.vscode/tasks.xsh run tcb-setup
          xonsh ./.vscode/tasks.xsh run tcb-build

      - name: Push OS Package to Platform
        shell: xonsh {0}
        env:
          PLATFORM_CLIENT_ID: ${{ secrets.PLATFORM_CLIENT_ID }}
          PLATFORM_CLIENT_SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
        run: |
          xonsh ./.vscode/tasks.xsh run tcb-setup
          xonsh ./.vscode/tasks.xsh run tcb-platform-push-ostree

      - name: Deploy to Fleet
        shell: xonsh {0}
        env:
          TASKS_OVERRIDE_ENV: "False"
          PLATFORM_CLIENT_ID: ${{ secrets.PLATFORM_CLIENT_ID }}
          PLATFORM_CLIENT_SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          xonsh ./.vscode/tasks.xsh run platform-update-fleet
