services:
  __container__-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/__container__-debug:${TAG}
    environment:
      - ACCEPT_FSL_EULA=1
    ports:
      # SSH debug
      - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}
      # gdbserver
      - ${DEBUG_PORT1}:${DEBUG_PORT1}
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    device_cgroup_rules:
      # ... for tty0
      - "c 4:* rmw"
      # ... for /dev/input devices
      - "c 13:* rmw"
      - "c 199:* rmw"
      # ... for /dev/dri devices
      - "c 226:* rmw"

  __container__:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/__container__:${TAG}
    environment:
      - ACCEPT_FSL_EULA=1
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    device_cgroup_rules:
      # ... for tty
      - "c 4:* rmw"
      # ... for /dev/input devices
      - "c 13:* rmw"
      - "c 199:* rmw"
      # ... for /dev/dri devices
      - "c 226:* rmw"
