services:


  xonsh:
    build:
      context: ../
      dockerfile: container/Containerfile.xonsh
      args:
        - BRANCH=${__TCD_BRANCH}
    image: torizonextras/xonsh:${__TCD_BRANCH}


  tasks:
    build:
      context: ../
      dockerfile: container/Containerfile.tasks
      args:
        - BRANCH=${__TCD_BRANCH}
        - REPO=toradex/vscode-torizon-templates
    image: torizonextras/torizon-dev-tasks:${__TCD_BRANCH}


  xonsh-wrapper:
    build:
      context: ../
      dockerfile: container/Containerfile.wrapper
      args:
        - BRANCH=${__TCD_BRANCH}
    image: torizonextras/xonsh-wrapper:${__TCD_BRANCH}


  torizon-dev:
    build:
      context: ../
      dockerfile: container/Containerfile.dev
      args:
        - BRANCH=${__TCD_BRANCH}
        - UID=${__TCD_UUID}
    image: torizonextras/torizon-dev:${__TCD_BRANCH}
    privileged: true
    network_mode: host
    environment:
      - APOLLOX_TEMPLATES_GIT_REPO=https://github.com/torizon/vscode-torizon-templates.git
      - APOLLOX_TEMPLATES_GIT_REPO_BRANCH=${__TCD_BRANCH}
      #- APOLLOX_TEMPLATES_GIT_TAG=
      - WSL_DISTRO_NAME=${WSL_DISTRO_NAME}
      - APOLLOX_CONTAINER=1
      - UUID=${__TCD_UUID}
      - DGID=${__TCD_DGID}
      - UUSER=${USER}
      - APOLLOX_WORKSPACE=${PWD}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/${__TCD_UUID}:/run/user/${__TCD_UUID}
      - /mnt:/mnt
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - ${HOME}/.tcd/:/home/torizon/.tcd/
      - ${PWD}:/workspace
      - ${PWD}:${PWD}
    container_name: torizon-dev-${__TCD_SHA_DIR}
    stdin_open: true
    tty: true
    pid: host
