name: Sanity Check
on:
  workflow_call:

jobs:
  spell-check:
    runs-on: ubuntu-24.04
    container:
      image: node:18
    name: Spell Check
    steps:
      - uses: actions/checkout@v4

      - name: cspell CLI Lint

        shell: bash

        run: |
          npm install git+https://github.com/streetsidesoftware/cspell-cli
          npx cspell-cli lint --relative


  check-eof-new-line:
    runs-on: ubuntu-24.04
    container:
      image: torizonextras/torizon-dev:dev
      options: --user root
    name: Check EOF New Line
    steps:
      - uses: actions/checkout@v4

      - name: Check EOF New Line

        shell: bash

        run: |
          xonsh ./scripts/valid-new-line.xsh

  check-json:
    runs-on: ubuntu-24.04
    container:
      image: torizonextras/torizon-dev:dev
      options: --user root
    name: Check JSON
    steps:
      - uses: actions/checkout@v4

      - name: Check JSON

        shell: bash

        run: |
          xonsh ./scripts/validate-json.xsh
